### ISSUE TITLE
Trade menus and items in item containers not showing

### ISSUE THREAD

**Issue by Ebracks** [Norbyte/bg3se#138]
Just downloaded the SE for patch 4 and everything is working with all my mods except for this one issue. When I go to open any trade menu nothing shows up. There's just no UI present but I can still press escape to exit. Similarly, when I open any item containers like crates or backpacks, the UI is there but all items inside are invisible and I have to hover over each individually to see what they are. I have a good amount of mods installed and have only been able to update a few of them (like improved UI) so one of these could be creating the issue but I was just wondering if anyone had experienced something similar. Game runs perfectly fine other than this. Thanks for updating this so quickly after the patch and if anyone has any answers for this that'd be great!

**Comment by seanyeo300** [comment]
I am getting the same issue, but for trade menu only

**Comment by Kambros** [comment]
If you have "Better Containers" Mod installed, update it. That should solve the missing items issue.

**Comment by Ebracks** [comment]
I already tried updating Better Containers but got nothing. I'll give it another shot and see if that fixes the issue.

**Comment by Ebracks** [comment]
Updated Better Containers again and reinitialized my files and the missing item issue was fixed! Thank you Kambros! Still having the trade menu issue so any help on that front would be greatly appreciated!

**Comment by Demiand7** [comment]
Maybe the problem is related to the "Slightly better trade menus" mod which is set as **"This mod is currently not supported by the author(s) and/or has issue(s) they are unable to fix yet."**

So, if you are using it you will not be able to see the trade menu

**Comment by Ebracks** [comment]
Yep Demiand7 that's exactly it. I just went and tried the same thing and found the issue, came back and you seem to have solved the same problem. For anyone else having the same issue, the culprit is likely the "Slightly better trade menus" by Caites. The mod is currently disabled on Vortex which is why it took me a little while to locate the issue but if you have the mod installed and can't see trade menus this is probably why. I deleted the mod from my mod manager and everything worked again with no issues to my save but your own mileage may vary. Hoping this mod gets updated and republished soon because it did really help with trading! Thanks everyone for your help!
