### ISSUE TITLE
Patch 3 + SExtender cause game to crash when starting.

### ISSUE THREAD

**Issue by Bogdanov89** [Norbyte/bg3se#63]
It may be obvious but just to report it either way, the latest patch 3 from 22 september combined with the currently available SExtender cause an unavoidable crash when starting Bg3.

Deleting the SExtender file from the game folder prevents the crash.

**Comment by Norbyte** [comment]
Should be fixed now.

**Comment by Golconda522** [comment]
I am still getting a crash right after the console appears and load script it just started today and not sure what happened but now I crash every time I start the game

**Comment by MatrixDJ96** [comment]
> I am still getting a crash right after the console appears and load script it just started today and not sure what happened but now I crash every time I start the game

We should wait new release...
